---
title: "Reproducible Research: Peer Assessment 1"
author: "Jim Callahan"
date: "September 13, 2015"
output: 
  html_document:
    keep_md: true
---

## Loading and preprocessing the data
```{r, echo=TRUE}
#### Set directory to the local GitHub project of this assignment.
setwd("~\\GitHub\\RepData_PeerAssessment1")

activity <- read.csv("activity.csv", 
                     na.strings = "NA", stringsAsFactors = FALSE )
activity$date <- as.Date(activity$date)

### Data is for October and November 2012 (61 days)
### In each hour there are 12 "five minute" intervals 
### (60/5 = 12 intervals per hour)
### There are 288 five minute intervals in a 24-hour day 
### (24 hours*12 intervals per hour = 288 intervals per 24 hours)
### In 61 days (24 hour days) there are 17,568 
### five minute intervals (61*288)
### There are 17,568 observations (records) 
### of which 2,304 (13.11%) of the "step" values are missing.

### WHAT DOES NOT MAKE SENSE?
### If there are 288 five minute intervals in a day
### and we number then 0 through 287
### and then we multiply by 5; 
### the highest interval should be (5*287=1435).
### YET, the max interval is 2355 
### and even the 3rd quintile is 1766.
### plot(activity$interval) # dense rectangular plot

### ANSWER: Series jumps from "55" to "100" on the hour
head(levels(as.factor(activity$interval)), 15)

### So, really, activity$hour should be understood 
### as a 4 digit number # (with leading zeros), 
### where the first twp digits are the hour 
### and the other two # digits are the minute (hhmm).

# Convert the interval to HHMM by formating with leading zero.
activity$HHMM <- sprintf("%04d",as.integer(activity$interval))
# Now we can combine date and time as a string
# and format the resulting string as a POSIX datetime string.
datetimestring     <- paste(activity$date, activity$HHMM)
activity$datetime  <- strptime(datetimestring, 
                               "%Y-%m-%d %H%M", tz = "")
```



## What is mean total number of steps taken per day?
```{r, echo=TRUE}
PerDay <- aggregate(steps ~ date, data=activity, sum)  
mean(PerDay$steps)
median(PerDay$steps) 
```


## What is the average daily activity pattern?
```{r, echo=FALSE}
hist(PerDay$steps, breaks=25, 
     main = paste("Histogram of Steps Per Day", 
                  "\n Mean = " , round(mean(PerDay$steps), digits=0),
                  "\n Median =", median(PerDay$steps) 
                  ) 
     )
```

## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
